services:
  server:
    image: kristofehl/bonfire-server
    container_name: s-bonfire-server
    network_mode: "host"
    depends_on:
      - mock_llm
    volumes:
      - type: bind
        source: ./config.json
        target: /app/bonfire-ml-src/config.json
  mock_llm:
    image: kristofehl/bonfire-mock-llm
    container_name: s-bonfire-mock-llm
    network_mode: "host"
  shell:
    image: kristofehl/bonfire-shell
    container_name: s-bonfire-shell
    network_mode: "host"
    restart: always
    stdin_open: true 
    tty: true
